# Generated by Django 3.1.7 on 2021-03-14 18:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDeConocimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaña',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField()),
                ('foto', models.ImageField(upload_to='fotos_campaña')),
                ('meta', models.TextField()),
                ('fechaCulminacion', models.DateTimeField(default=datetime.datetime.now)),
                ('clasificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=60)),
                ('avatar', models.ImageField(upload_to='fotos_perfil')),
                ('info', models.TextField()),
                ('estado', models.TextField()),
                ('seguir', models.BigIntegerField()),
                ('area', models.ManyToManyField(to='helpcom.AreaDeConocimiento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaña', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpcom.campaña')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpcom.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_publ', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_publicacion')),
                ('area', models.TextField(blank=True, null=True)),
                ('megusta', models.BigIntegerField(blank=True, null=True)),
                ('campaña', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpcom.campaña')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpcom.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpcom.publicacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpcom.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpcom.publicacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpcom.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='campaña',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpcom.usuario'),
        ),
    ]
